version: '3.4'

services:
  webgp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
      - DataBase__Self__User=${SELF_USER}
      - DataBase__Self__Password=${SELF_PASSWORD}
      - DataBase__Self__DataBase=${SELF_DB}
      - DataBase__Self__Server=${SELF_SERVER}
      - DataBase__Self__Port=${SELF_PORT}
      
      - DataBase__GPO__User=${GPO_USER}
      - DataBase__GPO__Password=${GPO_PASSWORD}
      - DataBase__GPO__DataBase=${GPO_DB}
      - DataBase__GPO__Server=${GPO_SERVER}
      - DataBase__GPO__Port=${GPO_PORT}

      - DataBase__GPC__User=${GPC_USER}
      - DataBase__GPC__Password=${GPC_PASSWORD}
      - DataBase__GPC__DataBase=${GPC_DB}
      - DataBase__GPC__Server=${GPC_SERVER}
      - DataBase__GPC__Port=${GPC_PORT}

      - DataBase__Donate__User=${DONATE_USER}
      - DataBase__Donate__Password=${DONATE_PASSWORD}
      - DataBase__Donate__DataBase=${DONATE_DB}
      - DataBase__Donate__Server=${DONATE_SERVER}
      - DataBase__Donate__Port=${DONATE_PORT}

      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - JWT__Key=${JWT_KEY}
    ports:
      - "${API_OUT_PORT}:80"
  self_db:
    platform: linux/x86_64
    environment:
      MARIADB_VERSION: "10.6"
      MARIADB_ROOT_PASSWORD: ${SELF_PASSWORD}
      MARIADB_DATABASE: ${SELF_DB}
    ports:
      - "${SELF_PORT}:3306"
    volumes:
      - ./self_db_data:/var/lib/mysql

  gp_db:
    platform: linux/x86_64
    environment:
      MARIADB_VERSION: "10.6"
      MARIADB_ROOT_PASSWORD: ${GP_PASSWORD}
      MARIADB_DATABASE: ${GP_DB}
    ports:
      - "${GP_PORT}:3306"
    volumes:
      - ./gp_db_data:/var/lib/mysql