version: '3.4'

services:
  webgp:
    image: ${DOCKER_REGISTRY-}webgp
    container_name: WebGP
    build:
      context: .
      dockerfile: WebGP/Dockerfile
    networks:
      - gp_net
    depends_on:
      - self_db
      - gp_db

  self_db:
    image: mariadb:10.6
    container_name: self_db
    networks:
      - gp_net
  gp_db:
    image: mariadb:10.6
    container_name: gp_db
    networks:
        - gp_net
networks:
  gp_net:
    driver: bridge