version: '3.4'

services:
  webgp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DataBase__Self__User=${SELF_USER}
      - DataBase__Self__Password=${SELF_PASSWORD}
      - DataBase__Self__DB=${SELF_DB}
    ports:
      - "1112:80"
  database:
    platform: linux/x86_64
    environment:
      MARIADB_VERSION: "10.6"
      MARIADB_ROOT_PASSWORD: ${SELF_PASSWORD}
    ports:
      - "1113:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql