version: '3.4'

services:
  webgp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "1112:80"
  database:
    platform: linux/x86_64
    environment:
      MARIADB_VERSION: "10.6"
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "1113:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql