version: '3.4'

services:
  webgp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
      - DataBase__Self__User=${SELF_USER}
      - DataBase__Self__Password=${SELF_PASSWORD}
      - DataBase__Self__DataBase=${SELF_DB}
      - DataBase__Self__Server=${SELF_SERVER}
      - DataBase__Self__Port=${SELF_PORT}

      - DataBase__GP__User=${GP_USER}
      - DataBase__GP__Password=${GP_PASSWORD}
      - DataBase__GP__DataBase=${GP_DB}
      - DataBase__GP__Server=${GP_SERVER}
      - DataBase__GP__Port=${GP_PORT}

      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - JWT__Key=${JWT_KEY}
    ports:
      - "${API_OUT_PORT}:80"
  database:
    platform: linux/x86_64
    environment:
      MARIADB_VERSION: "10.6"
      MARIADB_ROOT_PASSWORD: ${SELF_PASSWORD}
    ports:
      - "${SELF_PORT}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql