version: '3.4'

services:
  webgp:
    image: ${DOCKER_REGISTRY-}webgp
    container_name: WebGP
    build:
      context: .
      dockerfile: WebGP/Dockerfile
    networks:
      - WebGP_Net
    depends_on:
      - database
  database:
    image: mariadb:10.6
    container_name: MariaDB
    networks:
      - WebGP_Net
networks:
  WebGP_Net:
    driver: bridge