version: '3.4'

services:
  webgp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "1112:80"
  database:
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "1113:3306"
    volumes:
      - .\mariadb_data:/my/own/datadir