// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGP.Infrastructure.DataBase;

#nullable disable

namespace WebGP.Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("WebGP.Domain.Entities.Discord", b =>
                {
                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("discord_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid");

                    b.HasIndex(new[] { "DiscordId" }, "discord_id")
                        .IsUnique();

                    b.HasIndex(new[] { "Uuid" }, "uuid")
                        .IsUnique();

                    b.ToTable("discord", (string)null);
                });

            modelBuilder.Entity("WebGP.Domain.Entities.Online", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid");

                    b.Property<bool>("IsOp")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_op");

                    b.Property<string>("SkinUrl")
                        .HasColumnType("text")
                        .HasColumnName("skin_url");

                    b.Property<int?>("TimedId")
                        .HasColumnType("int(11)")
                        .HasColumnName("timed_id");

                    b.Property<int>("World")
                        .HasColumnType("int(11)")
                        .HasColumnName("world");

                    b.Property<double>("X")
                        .HasColumnType("double")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double")
                        .HasColumnName("y");

                    b.Property<double>("Z")
                        .HasColumnType("double")
                        .HasColumnName("z");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.ToTable("online", (string)null);
                });

            modelBuilder.Entity("WebGP.Domain.Entities.OnlineLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Sec")
                        .HasColumnType("int(11)")
                        .HasColumnName("sec");

                    b.HasKey("Id", "Day")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("online_logs", (string)null);
                });

            modelBuilder.Entity("WebGP.Domain.Entities.RoleWorkReadonly", b =>
                {
                    b.Property<string>("Icon")
                        .HasColumnType("mediumtext")
                        .HasColumnName("icon");

                    b.Property<int>("Id")
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("name")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("''");

                    b.ToTable((string)null);

                    b.ToView("role_work_readonly", (string)null);
                });

            modelBuilder.Entity("WebGP.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("datetime")
                        .HasColumnName("birthday_date");

                    b.Property<int?>("CardId")
                        .HasColumnType("int(11)")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("ConnectDate")
                        .HasColumnType("datetime")
                        .HasColumnName("connect_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<int>("Exp")
                        .HasColumnType("int(11)")
                        .HasColumnName("exp");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool?>("Male")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("male")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("Phone")
                        .HasColumnType("int(11)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("int(11)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("RoleTime")
                        .HasColumnType("datetime")
                        .HasColumnName("role_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("Work")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("work")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("WorkTime")
                        .HasColumnType("datetime")
                        .HasColumnName("work_time");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Phone" }, "phone")
                        .IsUnique();

                    b.HasIndex(new[] { "Uuid" }, "uuid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
