name: deploy

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  #run_test_build:
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #  - uses: actions/checkout@master
  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v3
  #    with:
  #      dotnet-version: 8.0.100-preview.2.23157.25
  #  - name: Restore dependencies
  #    run: dotnet restore ./src/WebGP/WebGP.csproj
  #  - name: Build
  #    run: dotnet build --no-restore ./src/WebGP/WebGP.csproj
  #  - name: Test
  #    run: dotnet test --no-build --verbosity normal ./src/WebGP/WebGP.csproj
  #    
  #    
  build_and_pub:
    needs: [run_test_build]
    
    runs-on: ubuntu-latest
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@master
    - run: ls -a
    - name: Build image
      run:  docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f ./src/WebGP/Dockerfile .
    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
    - name: Send webhook for deploy
      run: "curl -X POST ${{ secrets.DEPLOYMENT_SERVER }} --header \"Authorization: ${{ secrets.DEPLOYMENT_TOKEN }}\""
