name: deploy

on: 
   pull_request_target:
    types:
      - closed
    branches: [ "master" ]

jobs:
  build_and_pub:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@master
    - name: Build image
      run:  docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile ./WebGP/
    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
